### ISSUE TITLE
初期Arduinoプロジェクトを追加する。

### ISSUE THREAD

**Issue by nekakoshi** [kashiwa-geeks/arduino-raspberry-cds#1]
@mascii さんが [Arduino もくもく in 柏の葉KOIL](https://kashiwano-ha-geeks.connpass.com/) で作成したリソースをpushしてくれるはず。

**Comment by mascii** [comment]
# 予定
ArduinoのLチカなど、簡単なものは「スケッチの例」に入っているので省略します。

- [x] (Arduino) CdSに当たった光量に応じてLEDの光量を変える例
- [x] (Arduino + PC) CdSに当たった光量をPC側で取得する例
- [x] (Arduino + PC) 3色LEDの色をPC側からコマンドを送って変える例
- [x] (Arduino + Raspberry) Arduino側はCdSに当たった光量に応じて3色LEDの光量を変えつつ、Raspberry Pi側はサーバーとして機能しブラウザからの操作で3色LEDの色を変えることができる例
  - Raspberry Pi側はPythonではなくNode.jsになってしまいます。ご了承ください。

**Comment by nekakoshi** [comment]
タスク書き出しありがとうございます。
markdownでタスクの記述方法がありますので修正お願いします。
こんな感じです

```
- [ ] 
```

**Comment by nekakoshi** [comment]
Gitの利用方法は以下のような手順でできます。

```
$ brew install git ### Gitがインストールされていない場合
$ cd $ARDUINO_PAT ### arduinoのファイルがあるところです。
$ git init 
$ git remote add git@github.com:kashiwa-geeks/arduino-raspberry-cds.git
$ git pull origin HEAD
$ git add . 
$ git commit -m 'my first commit '
$ git push origin HEAD

```

**Comment by mascii** [comment]
`git push` をしようとすると権限が無いと出てしまいます。
`README.md` を GitHub上で編集しようとしても、書き込み権限がありませんと出てしまいます。

<img width="981" alt="2016-12-05 18 57 20" src="https://cloud.githubusercontent.com/assets/13311608/20880762/ceb93f82-bb1c-11e6-80ef-b1debf623931.png">

権限の方、ご確認いただけたらと思います。

**Comment by nekakoshi** [comment]
write権限追加しました。
pushできますか？

権限設計せねば。。。

**Comment by mascii** [comment]
pushできました！
`README.md` は作成中です。

**Comment by nekakoshi** [comment]
https://github.com/kashiwa-geeks/arduino-raspberry-cds/issues/1#issuecomment-264712487
の部分がタスクだと思ってたので、勘違いでした。

ただ、こちらpushしたらタスクをチェックして完了でいいと思います。

タスクに書いた内容を[wiki](https://github.com/kashiwa-geeks/arduino-raspberry-cds/wiki) に追加してもらえるといいかもしれませんね。

**Comment by mascii** [comment]
使い方とかを `README.md` に書くかwikiに書くか悩んでいたのですが、wikiに書くことにします！

**Comment by nekakoshi** [comment]
READMEはインストール手順や導入背景など、cloneしてくれた人が利用できる記述があるといいですよね。
wikiは全体構成やversion管理など記載してもらえると、
今後プロジェクトに参加した人が、「こんな感じで進めるのか」、「こんな構成・仕様なのか」とかわかりやすいですよね。

**Comment by mascii** [comment]
なるほど、 `README.md` の方にcloneしてくれた人向けの説明をざっくり書いてみました。

**Comment by nekakoshi** [comment]
イケてます！！
コメントした後にメンション入れてもらえると気づくのでお願いします。
@mascii 

その他タスクがなければ、クローズお願いします。

**Comment by mascii** [comment]
ありがとうございます！ @wl-harada
